name: Python CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/src" >> $GITHUB_ENV
      - name: Set dummy AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=dummy" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=dummy" >> $GITHUB_ENV
      - name: Run tests with coverage
        run: |
          coverage run -m pytest src/test/unit
          coverage report -m > cov.txt
          cat cov.txt
      - name: Upload coverage file
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: cov.txt

  coverage:
    name: Coverage Report
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: coverage-report
      - name: Show coverage summary and notify
        run: |
          cat cov.txt
          THRESHOLD=90
          ACTUAL=$(awk '/^TOTAL/ {print int($4)}' cov.txt)
          if [ "$ACTUAL" -lt "$THRESHOLD" ]; then
            DIFF=$((THRESHOLD - ACTUAL))
            echo "::warning ::Coverage is $ACTUAL%, which is $DIFF% below the required $THRESHOLD%."
          else
            DIFF=$((ACTUAL - THRESHOLD))
            echo "::notice ::Coverage is $ACTUAL%, which is $DIFF% above the required $THRESHOLD%."
          fi
      - name: Add coverage % to summary
        run: |
          ACTUAL=$(awk '/^TOTAL/ {print $4}' cov.txt)
          echo "### Coverage: $ACTUAL" >> $GITHUB_STEP_SUMMARY

  bandit:
    name: Bandit Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Bandit
        run: |
          pip install bandit
      - name: Run Bandit
        run: bandit -r src/ -lll

  radon:
    name: Radon Complexity Check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Radon
        run: |
          pip install radon
      - name: Run Radon
        run: radon cc src/ -nc
